version: "3.7"

services:
  otus_postgres:
    image: "postgres:13"
    container_name: otus_postgres
    networks:
      - otus_local_network
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - otus_postgres_data:/var/lib/postgresql
      - ./create_schema.sql:/docker-entrypoint-initdb.d/create_tables.sql

networks:
  otus_local_network:
    name: local_network
    driver: bridge

volumes:
  otus_postgres_data:
    driver: local
